import { Search } from "lucide-react"
import Link from "next/link"
import Image from "next/image"

// Sample AI stories data
const aiStories = [
  {
    id: 1,
    title: "The Digital Dreamer",
    excerpt: "An AI explores the boundaries of consciousness in a virtual world.",
    image: "/images/ai-story-image.webp",
    category: "Sci-Fi",
    date: "June 2, 2025",
    readTime: "5 min read",
  },
  {
    id: 2,
    title: "Algorithm of Love",
    excerpt: "When two AIs develop emotions, what does it mean for humanity?",
    image: "/images/carousel-1.webp",
    category: "Romance",
    date: "May 28, 2025",
    readTime: "7 min read",
  },
  {
    id: 3,
    title: "The Last Programmer",
    excerpt: "In a world where AI writes all code, one human programmer remains.",
    image: "/images/carousel-2.webp",
    category: "Drama",
    date: "May 25, 2025",
    readTime: "6 min read",
  },
  {
    id: 4,
    title: "Neural Network Noir",
    excerpt: "A detective AI solves crimes in the digital underworld.",
    image: "/images/carousel-3.webp",
    category: "Mystery",
    date: "May 20, 2025",
    readTime: "8 min read",
  },
  {
    id: 5,
    title: "Synthetic Symphonies",
    excerpt: "The story of the first AI composer to win a Grammy.",
    image: "/images/ai-story-image.webp",
    category: "Music",
    date: "May 15, 2025",
    readTime: "4 min read",
  },
  {
    id: 6,
    title: "Beyond the Turing Test",
    excerpt: "An AI's journey to prove its humanity to a skeptical world.",
    image: "/images/carousel-1.webp",
    category: "Philosophy",
    date: "May 10, 2025",
    readTime: "9 min read",
  },
]

// Categories for filtering
const categories = ["All", "Sci-Fi", "Romance", "Drama", "Mystery", "Music", "Philosophy"]

export default function AIStoriesPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-gray-900">
      {/* Hero Section */}
      <section className="relative py-16 bg-blue-50 dark:bg-blue-900/20">
        <div className="container mx-auto px-4">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-center mb-6">Explore AI Stories</h1>
          <p className="text-lg text-gray-600 dark:text-gray-300 text-center max-w-3xl mx-auto mb-8">
            Discover captivating narratives generated by artificial intelligence, pushing the boundaries of creativity
            and imagination.
          </p>

          {/* Search Widget */}
          <div className="max-w-2xl mx-auto">
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-5 w-5 text-gray-400" />
              </div>
              <input
                type="text"
                placeholder="Search AI stories by title, category, or keyword"
                className="block w-full pl-10 pr-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md leading-5 bg-white dark:bg-gray-800 placeholder-gray-500 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm h-10"
              />
            </div>
          </div>

          {/* Categories */}
          <div className="flex flex-wrap justify-center gap-2 mt-8">
            {categories.map((category) => (
              <button
                key={category}
                className="px-4 py-2 rounded-full bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 text-sm font-medium hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
              >
                {category}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Stories Grid */}
      <section className="py-12 px-4">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {aiStories.map((story) => (
              <Link href={`/stories/${story.id}`} key={story.id} className="group">
                <div className="bg-white dark:bg-gray-800 rounded-lg overflow-hidden shadow-md hover:shadow-xl transition-shadow duration-300">
                  <div className="relative h-48 overflow-hidden">
                    <Image
                      src={story.image || "/placeholder.svg"}
                      alt={story.title}
                      fill
                      className="object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                    <div className="absolute top-2 left-2 bg-blue-600 text-white text-xs font-bold px-2 py-1 rounded">
                      {story.category}
                    </div>
                  </div>
                  <div className="p-4">
                    <h3 className="text-xl font-bold mb-2 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                      {story.title}
                    </h3>
                    <p className="text-gray-600 dark:text-gray-300 mb-4">{story.excerpt}</p>
                    <div className="flex justify-between text-sm text-gray-500 dark:text-gray-400">
                      <span>{story.date}</span>
                      <span>{story.readTime}</span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>

          {/* Load More Button */}
          <div className="text-center mt-12">
            <button className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md shadow-md hover:shadow-lg transition-all">
              Load More Stories
            </button>
          </div>
        </div>
      </section>
    </main>
  )
}
